import crafttweaker.item.IItemStack;

import mods.jei.JEI;

/*

Recipes for Elician (Factory) BY Dmitry Sidorov (https://justydev.ru)

*/

var removeIngredients as IItemStack[] = [
	// Misc
	<minecraft:command_block_minecart>,
	<minecraft:repeating_command_block>,
	<minecraft:chain_command_block>,
	<minecraft:barrier>,
	<minecraft:structure_void>,
	<minecraft:structure_block>,
	<minecraft:command_block>,

	<thermalfoundation:bait:1>,
	<thermalfoundation:bait:2>,
	<thermalfoundation:bait>,
	<thermalfoundation:coin:*>,
	<thermalfoundation:fertilizer:2>,
	<thermalfoundation:upgrade:1>,
	<thermalfoundation:upgrade:2>,
	<thermalfoundation:upgrade:3>,
	<thermalfoundation:upgrade:33>,
	<thermalfoundation:upgrade:34>,
	<thermalfoundation:upgrade:35>,
	<thermalfoundation:upgrade:256>,
	<thermalfoundation:upgrade>,

	<thermalexpansion:cache>,

	<nuclearcraft:ore>,
	<nuclearcraft:ore:1>,
	<nuclearcraft:ore:2>,
	<nuclearcraft:dust>,
	<nuclearcraft:dust:1>,
	<nuclearcraft:dust:2>,
	<nuclearcraft:ingot>,
	<nuclearcraft:ingot:1>,
	<nuclearcraft:ingot:2>,
	<nuclearcraft:ingot_block>,
	<nuclearcraft:ingot_block:1>,
	<nuclearcraft:ingot_block:2>,
	<nuclearcraft:fission_controller_idle>,
	<minecraft:spawn_egg:*>,
	<minecraft:end_portal_frame>,
	<alchemistry:milk>,
	<energycontrol:afsu_upgrade_kit>,
	<forestry:stamps:*>,

	//Na na na na na na na na HEY HEY HEY GOODBYE ... to certus quartz
	<appliedenergistics2:certus_quartz_wrench>,
	<appliedenergistics2:material:3>,
	<appliedenergistics2:material:45>,
	<appliedenergistics2:material:40>,

	//explousans fix

	<appliedenergistics2:facade>.withTag({damage: 0, item: "minecraft:tnt"}),
	<forestry:rainmaker>,
	<minecraft:tnt>,

	<energycontrol:afb:*>,
	<energycontrol:afsu>,

	<thermalfoundation:ore:8>,
	<thermalfoundation:ore:6>,

	// Remove Iridium
	<thermalfoundation:ore:7>,
	<thermalfoundation:storage:7>,
	<thermalfoundation:material:71>,
	<thermalfoundation:material:135>,
	<thermalfoundation:material:199>,
	<thermalfoundation:material:327>,

	// Remove Constantan
	<thermalfoundation:material:100>,
	<thermalfoundation:material:164>,
	<thermalfoundation:material:228>,
	<thermalfoundation:material:356>,
	<thermalfoundation:storage_alloy:4>,
	<thermalfoundation:material:27>,
	<thermalfoundation:material:256>,
	<thermalfoundation:material:257>,
	<thermalfoundation:material:258>,
	<thermalfoundation:material:259>,
	<thermalfoundation:material:260>,
	<thermalfoundation:material:261>,
	<thermalfoundation:material:262>,
	<thermalfoundation:material:263>,
	<thermalfoundation:material:264>,
	<thermalfoundation:material:288>,
	<thermalfoundation:material:291>,
	<thermalfoundation:material:292>,
	<thermalfoundation:material:294>,
	<thermalfoundation:dye>,
	<thermalfoundation:dye:1>,
	<thermalfoundation:dye:2>,
	<thermalfoundation:dye:3>,
	<thermalfoundation:dye:4>,
	<thermalfoundation:dye:5>,
	<thermalfoundation:dye:6>,
	<thermalfoundation:dye:7>,
	<thermalfoundation:dye:8>,
	<thermalfoundation:dye:9>,
	<thermalfoundation:dye:10>,
	<thermalfoundation:dye:11>,
	<thermalfoundation:dye:12>,
	<thermalfoundation:dye:13>,
	<thermalfoundation:dye:14>,
	<thermalfoundation:dye:15>,
	<thermalfoundation:security>,
	<thermalfoundation:geode>,
	<thermalfoundation:material:865>,
	<thermalfoundation:material:816>,
	<thermalfoundation:material:817>,
	<thermalfoundation:material:818>,
	<thermalfoundation:material:819>,
	<thermalfoundation:material:832>,
	<thermalfoundation:material:833>,
	<thermalfoundation:material:514>,
	<thermalfoundation:glass_alloy:4>,
	<thermalfoundation:glass:7>,
	<thermalfoundation:glass:8>,
	<thermalfoundation:storage_resource:1>,
	<thermalfoundation:material:802>,
	<nuclearcraft:ingot_block:12>,
	<nuclearcraft:turbine_dynamo_coil:2>,
	<nuclearcraft:ingot:12>,
	<nuclearcraft:dust:12>,
	<thermalfoundation:ore:4>,
	<thermalfoundation:storage:4>,
	<thermalfoundation:glass:4>,
	<thermalfoundation:material:68>,
	<thermalfoundation:material:132>,
	<thermalfoundation:material:196>,
	<thermalfoundation:material:324>,

	<thermalfoundation:coin:103>,
    <thermalfoundation:coin:102>,
    <thermalfoundation:coin:101>,
    <thermalfoundation:coin:100>,
    <thermalfoundation:coin:99>,
    <thermalfoundation:coin:98>,
    <thermalfoundation:coin:97>,
    <thermalfoundation:coin:96>,
    <thermalfoundation:coin:72>,
    <thermalfoundation:coin:71>,
    <thermalfoundation:coin:70>,
    <thermalfoundation:coin:69>,
    <thermalfoundation:coin:68>,
    <thermalfoundation:coin:67>,
    <thermalfoundation:coin:66>,
    <thermalfoundation:coin:65>,
    <thermalfoundation:coin:64>,
    <thermalfoundation:coin:1>,
    <thermalfoundation:coin>,

	// AE Lumen Paintballs
	<appliedenergistics2:paint_ball:20>,
	<appliedenergistics2:paint_ball:21>,
	<appliedenergistics2:paint_ball:22>,
	<appliedenergistics2:paint_ball:23>,
	<appliedenergistics2:paint_ball:24>,
	<appliedenergistics2:paint_ball:25>,
	<appliedenergistics2:paint_ball:26>,
	<appliedenergistics2:paint_ball:27>,
	<appliedenergistics2:paint_ball:28>,
	<appliedenergistics2:paint_ball:29>,
	<appliedenergistics2:paint_ball:30>,
	<appliedenergistics2:paint_ball:31>,
	<appliedenergistics2:paint_ball:32>,
	<appliedenergistics2:paint_ball:33>,
	<appliedenergistics2:paint_ball:34>,
	<appliedenergistics2:paint_ball:35>,

	//shulkers delete
	<ironchest:iron_shulker_box_white:*>,
	<ironchest:iron_shulker_box_orange:*>,
	<ironchest:iron_shulker_box_magenta:*>,
	<ironchest:iron_shulker_box_yellow:*>,
	<ironchest:iron_shulker_box_pink:*>,
	<ironchest:iron_shulker_box_silver:*>,
	<ironchest:iron_shulker_box_purple:*>,
	<ironchest:iron_shulker_box_brown:*>,
	<ironchest:iron_shulker_box_red:*>,
	<ironchest:iron_shulker_box_black:*>,
	<ironchest:iron_shulker_box_green:*>,
	<ironchest:iron_shulker_box_blue:*>,
	<ironchest:iron_shulker_box_cyan:*>,
	<ironchest:iron_shulker_box_gray:*>,
	<ironchest:iron_shulker_box_lime:*>,
	<ironchest:iron_shulker_box_light_blue:*>,

	<ironchest:diamond_obsidian_shulker_upgrade>,
	<ironchest:vanilla_copper_shulker_upgrade>,
	<ironchest:vanilla_iron_shulker_upgrade>,
	<ironchest:iron_gold_shulker_upgrade>,
	<ironchest:gold_diamond_shulker_upgrade>,
	<ironchest:copper_silver_shulker_upgrade>,
	<ironchest:silver_gold_shulker_upgrade>,
	<ironchest:copper_iron_shulker_upgrade>,
	<ironchest:diamond_crystal_shulker_upgrade>,

	<minecraft:white_shulker_box>,
	<minecraft:orange_shulker_box>,
	<minecraft:magenta_shulker_box>,
	<minecraft:yellow_shulker_box>,
	<minecraft:light_blue_shulker_box>,
	<minecraft:lime_shulker_box>,
	<minecraft:pink_shulker_box>,
	<minecraft:gray_shulker_box>,
	<minecraft:silver_shulker_box>,
	<minecraft:black_shulker_box>,
	<minecraft:red_shulker_box>,
	<minecraft:green_shulker_box>,
	<minecraft:brown_shulker_box>,
	<minecraft:blue_shulker_box>,
	<minecraft:purple_shulker_box>,
	<minecraft:cyan_shulker_box>,
	<minecraft:shulker_shell>,
	<thermalexpansion:morb>.withTag({Generic: 1 as byte, id: "minecraft:shulker"}),

	//delete beds
	<minecraft:bed:2>,
	<minecraft:bed:3>,
	<minecraft:bed:4>,
	<minecraft:bed:5>,
	<minecraft:bed:6>,
	<minecraft:bed:7>,
	<minecraft:bed:8>,
	<minecraft:bed:9>,
	<minecraft:bed:10>,
	<minecraft:bed:11>,
	<minecraft:bed:12>,
	<minecraft:bed:13>,
	<minecraft:bed:14>,
	<minecraft:bed:15>,

    <minecraft:knowledge_book>,
    <minecraft:wooden_hoe>,
	<minecraft:wooden_axe>,
	<minecraft:wooden_shovel>,
	<minecraft:wooden_sword>,
	<ic2:te:82>,

	<minecraft:chainmail_chestplate>,
	<minecraft:chainmail_leggings>,
	<minecraft:chainmail_boots>,
	<minecraft:chainmail_helmet>,
	<minecraft:wooden_pickaxe>,

	<ic2:iridium_drill:*>,
	<ic2:te:68>,
	<ic2:te:69>,
	<ic2:te:89>,

	<draconicevolution:celestial_manipulator>,

	<appliedenergistics2:nether_quartz_cutting_knife>,
	<appliedenergistics2:certus_quartz_cutting_knife>
];

for ingredient in removeIngredients {
	removeExist(ingredient);
	JEI.removeAndHide(ingredient);
}

//remove Categories

JEI.hideCategory("thermaldynamics.covers");